import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "../styles/reset.css";
import "../styles/variables.css";
import "../styles/global.css";

import ClientLayout from "./clientLayout";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vladislav Zhuravskii - my Webpage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${firaSans.variable}`}>
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
